// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	session "github.com/bradenrayhorn/ledger-protos/session"
	mock "github.com/stretchr/testify/mock"
)

// SessionAuthenticatorServer is an autogenerated mock type for the SessionAuthenticatorServer type
type SessionAuthenticatorServer struct {
	mock.Mock
	session.UnimplementedSessionAuthenticatorServer
}

// Authenticate provides a mock function with given fields: _a0, _a1
func (_m *SessionAuthenticatorServer) Authenticate(_a0 context.Context, _a1 *session.SessionAuthenticateRequest) (*session.SessionAuthenticateResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *session.SessionAuthenticateResponse
	if rf, ok := ret.Get(0).(func(context.Context, *session.SessionAuthenticateRequest) *session.SessionAuthenticateResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.SessionAuthenticateResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *session.SessionAuthenticateRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
