version: '3'

networks:
  test-network:
    driver: bridge

services:
  tests:
    build:
      context: .
      dockerfile: ./test.Dockerfile
    environment:
      - "PG_HOST=db"
      - "PG_PORT=5432"
      - "PG_USERNAME=postgres"
      - "PG_PASSWORD=password"
      - "PG_DATABASE=ledger_core"
    networks:
      - test-network
    volumes:
      - ./reports:/go/src/app/reports
    depends_on:
      - db
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - ./sql/migrations:/migrations
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=ledger_core"
    restart: on-failure
    networks:
      - test-network
